# Render Static Site configuration for Next.js static export
services:
  - type: static
    name: costikfinans
    env: static
    buildCommand: pnpm install --frozen-lockfile && pnpm run build
    staticPublishPath: out
    pullRequestPreviewsEnabled: true
    customDomains:
      - name: costikfinans.site
        certificateSource: letsencrypt
    headers:
      - path: /service-worker.js
        name: Cache-Control
        value: no-cache
      - path: /_next/static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    routes:
      - type: rewrite
        source: /_next/static/*
        destination: /_next/static/*
      - type: rewrite
        source: /(.*)
        destination: /$1
