services:
  - type: web
    name: costik-finans
    env: static
    plan: free
    buildCommand: |
      corepack enable
      corepack prepare pnpm@latest --activate
      export npm_config_yes=true
      export npm_config_audit=false
      export npm_config_fund=false
      pnpm install --shamefully-hoist --no-frozen-lockfile
      pnpm run build
    staticPublishPath: out
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        sync: false
