services:
- type: static
  name: Finans-static
  env: static
  buildCommand: ""
  staticPublishPath: .
  headers:
    - path: /sw.js
      name: Cache-Control
      value: no-cache
    - path: /workbox-*.js
      name: Cache-Control
      value: no-cache
