services:
  - type: web
    name: costik-finans
    env: node
    plan: free
    runtime: node
    buildCommand: |
      corepack enable
      corepack prepare pnpm@8.15.8 --activate
      pnpm install --frozen-lockfile
      pnpm run build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.18.0
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: NPM_CONFIG_LEGACY_PEER_DEPS
        value: true
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        sync: false
